/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/novo`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/laudo/__tests__/[id].test`; params?: Router.UnknownInputParams; } | { pathname: `/laudo/__tests__/editar.test`; params?: Router.UnknownInputParams; } | { pathname: `/laudo/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/laudo/[id]/editar`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/novo`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/laudo/__tests__/[id].test`; params?: Router.UnknownOutputParams; } | { pathname: `/laudo/__tests__/editar.test`; params?: Router.UnknownOutputParams; } | { pathname: `/laudo/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/laudo/[id]/editar`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/novo${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/laudo/__tests__/[id].test${`?${string}` | `#${string}` | ''}` | `/laudo/__tests__/editar.test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/novo`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/laudo/__tests__/[id].test`; params?: Router.UnknownInputParams; } | { pathname: `/laudo/__tests__/editar.test`; params?: Router.UnknownInputParams; } | `/laudo/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/laudo/${Router.SingleRoutePart<T>}/editar${`?${string}` | `#${string}` | ''}` | { pathname: `/laudo/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/laudo/[id]/editar`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
